//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exception_Filter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MVC_PracticeEntities : DbContext
    {
        public MVC_PracticeEntities()
            : base("name=MVC_PracticeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Async> tbl_Async { get; set; }
        public virtual DbSet<tblError_Log> tblError_Log { get; set; }
    
        public virtual int Usp_Error_Log(string gUID, string error_Name, string error_Message, string error_StackTrace, string error_ControllerName, string error_ActionName, string error_Time, string erro_SystemIP, string error_MacAddress, string error_PublicID, string error_UserName, string error_SystemName, string error_Browser)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(string));
    
            var error_NameParameter = error_Name != null ?
                new ObjectParameter("Error_Name", error_Name) :
                new ObjectParameter("Error_Name", typeof(string));
    
            var error_MessageParameter = error_Message != null ?
                new ObjectParameter("Error_Message", error_Message) :
                new ObjectParameter("Error_Message", typeof(string));
    
            var error_StackTraceParameter = error_StackTrace != null ?
                new ObjectParameter("Error_StackTrace", error_StackTrace) :
                new ObjectParameter("Error_StackTrace", typeof(string));
    
            var error_ControllerNameParameter = error_ControllerName != null ?
                new ObjectParameter("Error_ControllerName", error_ControllerName) :
                new ObjectParameter("Error_ControllerName", typeof(string));
    
            var error_ActionNameParameter = error_ActionName != null ?
                new ObjectParameter("Error_ActionName", error_ActionName) :
                new ObjectParameter("Error_ActionName", typeof(string));
    
            var error_TimeParameter = error_Time != null ?
                new ObjectParameter("Error_Time", error_Time) :
                new ObjectParameter("Error_Time", typeof(string));
    
            var erro_SystemIPParameter = erro_SystemIP != null ?
                new ObjectParameter("Erro_SystemIP", erro_SystemIP) :
                new ObjectParameter("Erro_SystemIP", typeof(string));
    
            var error_MacAddressParameter = error_MacAddress != null ?
                new ObjectParameter("Error_MacAddress", error_MacAddress) :
                new ObjectParameter("Error_MacAddress", typeof(string));
    
            var error_PublicIDParameter = error_PublicID != null ?
                new ObjectParameter("Error_PublicID", error_PublicID) :
                new ObjectParameter("Error_PublicID", typeof(string));
    
            var error_UserNameParameter = error_UserName != null ?
                new ObjectParameter("Error_UserName", error_UserName) :
                new ObjectParameter("Error_UserName", typeof(string));
    
            var error_SystemNameParameter = error_SystemName != null ?
                new ObjectParameter("Error_SystemName", error_SystemName) :
                new ObjectParameter("Error_SystemName", typeof(string));
    
            var error_BrowserParameter = error_Browser != null ?
                new ObjectParameter("Error_Browser", error_Browser) :
                new ObjectParameter("Error_Browser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Error_Log", gUIDParameter, error_NameParameter, error_MessageParameter, error_StackTraceParameter, error_ControllerNameParameter, error_ActionNameParameter, error_TimeParameter, erro_SystemIPParameter, error_MacAddressParameter, error_PublicIDParameter, error_UserNameParameter, error_SystemNameParameter, error_BrowserParameter);
        }
    }
}
