//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exception_Filter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblError_Log
    {
        public int Error_ID { get; set; }
        public string GUID { get; set; }
        public string Error_Name { get; set; }
        public string Error_Message { get; set; }
        public string Error_StackTrace { get; set; }
        public string Error_ControllerName { get; set; }
        public string Error_ActionName { get; set; }
        public string Error_Time { get; set; }
        public string Erro_SystemIP { get; set; }
        public string Error_MacAddress { get; set; }
        public string Error_PublicID { get; set; }
        public string Error_UserName { get; set; }
        public string Error_SystemName { get; set; }
        public string Error_Browser { get; set; }
    }
}
